// svelte_demo/src/NewTodo.svelte
<script>
	import { createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();

  let todo = '';

  function updateTodo() {
    dispatch('updateTodos', {
      todo
    });
    todo = '';
  }
</script>

<form on:submit|preventDefault={updateTodo}>
  <input name="todo" type="text" bind:value={todo}>
  <button type="submit">Add Todo</button>
</form>

// angular_demo/src/app/new-todo/new-todo.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-new-todo',
  templateUrl: './new-todo.component.html',
  styleUrls: ['./new-todo.component.css']
})
export class NewTodoComponent {
  todoText='';
  @Output() newTodoEvent = new EventEmitter<string>();
  addTodo(event: Event) {
    event.preventDefault();
    this.newTodoEvent.emit(this.todoText);
  }
}

<form (ngSubmit)="addTodo($event)">
  <label for="name">New Todo: </label>
  <input type="text" [(ngModel)]="todoText" name="todoText">
  <button type="submit">Add Todo</button>
</form>
