// react_demo/src/App.js
import { useEffect, useState } from "react";
import NewTodo from "./NewTodo";
import Todos from "./Todos";

function App() {
  const [todoList, setTodoList] = useState([]);

  useEffect(() => {
    const persistedTodoList = JSON.parse(localStorage.getItem('todos'));

    if (persistedTodoList) {
      setTodoList(persistedTodoList);
    }
  }, []);

  return (
    <div>
      <h1>TODO App</h1>
      <h2>React</h2>
      <h3>TODOs</h3>
      <Todos todoList={todoList} />
      <NewTodo setTodoList={setTodoList} />
    </div>
  );
};

export default App;

// svelte_demo/src/App.svelte
<script>
  import NewTodo from './NewTodo.svelte';
  import Todos from './Todos.svelte';

  let todos = [];

  function updateTodos (event) {
    todos = [...todos, event.detail.todo];
  }

</script>

<main>
  <h1>TODO App</h1>
  <h2>Svelte</h2>
  <h3>TODOs</h3>
  <Todos todos={todos} />
  <NewTodo on:updateTodos={updateTodos} />
</main>

<style>
</style>
