// react_demo/src/App.js
import { useEffect, useState } from "react";
import NewTodo from "./NewTodo";
import Todos from "./Todos";
import './App.css';

function App() {
  const [todoList, setTodoList] = useState([]);

  useEffect(() => {
    const persistedTodoList = JSON.parse(localStorage.getItem('todos'));

    if (persistedTodoList) {
      setTodoList(persistedTodoList);
    }
  }, []);

  return (
    <div>
      <h1>TODO App</h1>
      <h2>React</h2>
      <h3>TODOs</h3>
      <Todos todoList={todoList} />
      <NewTodo setTodoList={setTodoList} />
    </div>
  );
};

export default App;

// angular_demo/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'TODO App';
  todoList: string[] = [];

  ngOnInit(): void {
    const persistedTodoList = localStorage.getItem('todos');

    if (persistedTodoList) {
      this.todoList = JSON.parse(persistedTodoList);
    }
  }

  addNewTodo(newTodo: string) {
    this.todoList.push(newTodo);
    localStorage.setItem('todos', JSON.stringify(this.todoList));
  }
}

<h1>{{title}}</h1>
<h2>Angular</h2>
<app-todos [todoList]="todoList"></app-todos>
<app-new-todo (newTodoEvent)="addNewTodo($event)"></app-new-todo>
